version: 0.2

phases:
  build:
    commands:
      - export BUCKET=yoppy-codepipeline-test-bucket
      - aws cloudformation package --template-file template.yaml --s3-bucket $BUCKET --output-template-file outputtemplate.yaml --capabilities CAPABILITY_NAMED_IAM


artifacts:
  type: zip
  files:
    - template.yaml
    - outputtemplate.yaml